import { configApp } from '@/constants/config';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: `Login - ${configApp.appName}`,
  description: 'Generated by create next app',
}
export function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'vi' }];
}
export default async function LoginLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode,
  params: {
    locale: string
  }
}) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    //
  }
  return (
    <html lang="en">
      <body className={inter.className}>
          <NextIntlClientProvider locale={locale} messages={messages}>
              {children}
          </NextIntlClientProvider>
      </body>
    </html>
  )
}
